language: c
#solution: KalturaClient.sln
install:
    - sudo apt-get -y install mono-devel mono-gmc
script: 
    - xbuild KalturaClient.sln && cd ./KalturaClientTester/bin/Debug/ &&  mono KalturaClientTester.exe
