language: c

#solution: KalturaClient.sln
install:
    - sudo apt-get update && sudo apt-get -y install mono-complete wget
script: 
    #- wget -q 'http://mxr.mozilla.org/seamonkey/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1' -O "/tmp/certdata.txt" 
    #- mozroots --import --file /tmp/certdata.txt
    - sed -i "s@https://www.kaltura.com@http://www.kaltura.com@g" KalturaClientTester/KalturaClientTester.cs    
    - xbuild KalturaClient.sln && cd ./KalturaClientTester/bin/Debug/ &&  echo | mono KalturaClientTester.exe
notifications:
 email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
      - Noad.arad@kaltura.com
      - Elad.cohen@kaltura.com
      - Jonathan.Kanarek@kaltura.com
    on_success: change
    on_failure: always

